name: matilda
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12.3
  - numpy
  - tifffile
  - pandas
  - scipy
  - matplotlib
  - pyfai
  - xarray
  - requests
  - pip
  
  - pip:
    - h5py

